### ISSUE TITLE
inefficiency of inflect.py

### ISSUE THREAD

**Issue by jonorthwash** [fergusq/tampio#3]
Currently [inflect.py](https://github.com/fergusq/tampio/blob/master/inflect.py) uses a number of dictionaries, a series of embedded if statements, sub-string matching, and sub-string replacement to inflect nouns.

Walking a transducer, such as that of [omorfi](https://github.com/Flammie/omorfi) or [apertium-fin](https://github.com/flammie/apertium-fin), using [HFST's python library](https://hfst.github.io/python/3.12.2/index.html) or similar, should be a less costly way to implement the same functionality, and should take an order of magnitude or so less code to implement.

**Comment by fergusq** [comment]
Thanks for your interest in the project!

inflect.py is a wrapper to the original [inflect_word.py](https://github.com/fergusq/tampio/blob/master/voikko/inflect_word.py) and [voikkoinfl.py](https://github.com/fergusq/tampio/blob/master/voikko/voikkoinfl.py) provided with the [Voikko distribution](https://github.com/voikko/corevoikko/) that I have ported to Python 3. As Voikko doesn't inflect abbreviations, one-letter-nouns or number symbols, I created inflect.py that will inflect them and call the original implementation for other words. It uses a really basic algorithm with hard-coded case suffixes.

It is true that Voikko's Python scripts are not ideal and indeed I had to extend them in order to make them usable. I have tested replacing Voikko with omorfi, but had problems with installing it on some of my computers (running Fedora). Considering that I aim for maximum portability and that Voikko is already available on most common package repositories for Ubuntu, Debian and Fedora, I decided to continue using it for now.

In the future I might look into supporting both Voikko and omorfi, but it is not of a very high priority.
